name: Copy index.html to Server

# index.html 파일이 변경되거나 수동트리거시 워크플로우를 실행하도록 설정
on:
  push:
    paths:
      - 'index.html'  # 변경된 파일 경로
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions의 Ubuntu 환경에서 실행
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 리포지토리를 체크아웃

      - name: Set up SSH key for server access
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # 비공개 키를 저장
          chmod 600 ~/.ssh/id_rsa  # 비공개 키의 권한 설정
          ls -l ~/.ssh
          pwd
          ls -l
          cat index.html
         # touch ~/.ssh/known_hosts
         # chmod 600 ~/.ssh/known_hosts  # 권한 설정
         # ssh-keyscan -H -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || echo "Failed to add SSH key"  # 서버의 SSH 키를 known_hosts에 추가
         # cat ~/.ssh/known_hosts  # known_hosts 파일 내용 확인
        
      - name: Copy index.html to the server
        run: |
          # 서버에 파일을 복사
          scp -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} index.html ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html/
          ls -l
          # 파일 복사가 완료되었는지 확인 (서버에서 ls 명령어로 확인)
          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "ls -l /var/www/html/"
